const express = require("express");
const router = express.Router();

const authRoutes = require("./auth.route");
const productRoutes = require("./product.route");
const categoryRoutes = require("./category.route");
const subCategoryRoutes = require("./subCategory.route");
const cartRoutes = require("./cart.route");
const wishlistRoutes = require("./wishlist.route");
const couponRoutes = require("./coupon.router");
const orderRoutes = require("./order.route");
const adminOrderRoutes = require("./adminOrder.route");
const dashboardRoutes = require("./dashboard.route");
const exportRoutes = require("./export.route");
const searchRoutes = require("./search.route");
const notificationRoutes = require("./notification.route");
const adminCartRoutes = require("./adminCart.route");
const adminWishlistRoutes = require("./adminWishlist.route");

router.use("/admin/export", exportRoutes);
router.use("/auth", authRoutes);
router.use("/products", productRoutes);
router.use("/categories", categoryRoutes);
router.use("/subcategories", subCategoryRoutes);
router.use("/carts", cartRoutes);
router.use("/wishlist", wishlistRoutes);
router.use("/coupons", couponRoutes);
router.use("/orders", orderRoutes);
// router.use("/api/admin/orders", adminOrderRoutes);
router.use("/admin/orders", adminOrderRoutes);
router.use("/admin/dashboard", dashboardRoutes);
router.use("/admin/cart", adminCartRoutes);
router.use("/admin/wishlists", adminWishlistRoutes);
router.get("/search",searchRoutes);
router.use("/notifications", notificationRoutes);
module.exports = router;
